version: '3.9'

services:
  app:
    build: .
    ports:
      - '4000:4000'
    env_file:
      - ${ENV_FILE} # ENV_FILE lấy từ file .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
